# Generated by Django 4.1.2 on 2022-12-04 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgoraWrite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('contents', models.TextField(verbose_name='contents')),
                ('writerDt', models.DateTimeField(auto_now_add=True, verbose_name='writerDt')),
                ('updateDt', models.DateTimeField(auto_now=True, verbose_name='updateDt')),
                ('hits', models.PositiveIntegerField(default=0, verbose_name='hits')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='likes')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='writer')),
            ],
            options={
                'verbose_name': 'agora',
                'verbose_name_plural': 'agora',
                'db_table': 'agora',
            },
        ),
    ]
