# Generated by Django 4.1.2 on 2022-12-04 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agorawrite',
            options={},
        ),
        migrations.AlterModelTable(
            name='agorawrite',
            table=None,
        ),
    ]
